theme: jekyll-theme-hacker
title: "Javascript UI"
description: "Javascript UI for Javascript lesson hacks. I am doing a database and table featuring chemical compounds containing benzene."
gitorg: "https://github.com/A1234l/Final-Javascript-Implementation"
google_analytics:
